export function loadLanguage(ext: string): string {
  const map: Record<string, string> = {
    'json': 'json',
    'jsonl': 'json',
    'yaml': 'yaml',
    'yml': 'yaml',
    'py': 'python',
    'js': 'javascript',
    'ts': 'typescript',
    'jsx': 'jsx',
    'tsx': 'tsx',
    'xml': 'xml',
    'html': 'html',
    'css': 'css',
    'scss': 'css',
    'less': 'css',
    'md': 'markdown',
    'markdown': 'markdown',
    'txt': 'text',
    'csv': 'text',
    'sql': 'sql',
    'java': 'text',
    'cpp': 'text',
    'c': 'text',
    'h': 'text',
    'sh': 'shell',
    'bash': 'shell',
    'zsh': 'shell',
    'go': 'text',
    'rs': 'text',
    'rb': 'text',
    'php': 'text',
    'pl': 'text',
    'dockerfile': 'text',
    'env': 'text',
    'cfg': 'text',
    'ini': 'text',
    'toml': 'toml',
  };
  return map[ext] || 'text';
}
